import 'package:flutter/material.dart';

const Map<String, Map<String, String>> _translations = {
  'de': {
    'appTitle': 'Boxing App',
    'tagline': 'Train. Track. Win.',
    'timer': 'Timer',
    'stopwatch': 'Stoppuhr',
    'interval': 'Intervalle',
    'strength': 'Kraftübungen',
    'trainingPlan': 'Trainingsplan',
    'logbook': 'Logbuch',
    'settings': 'Einstellungen',
    'comingSoon': 'Bald verfügbar',
    'colorDesign': 'Farbdesign',
    'colorDesignSubtitle': 'Standard: Rot -- wähle deine eigene Akzentfarbe',
    'language': 'Sprache',
    'start': 'Start',
    'pause': 'Pause',
    'reset': 'Reset',
    'timeUp': 'Zeit abgelaufen!',
    'trainingDone': 'Training beendet',
    'round': 'Runde',
    'rounds': 'Runden',
    'roundDuration': 'Rundendauer',
    'min': 'Min',
    'sec': 'Sek',
    'soundToggleTitle': 'Signalton bei Zeitablauf',
    'soundToggleSubtitle': 'Boxglocke abspielen, wenn der Timer abläuft',
    'colorRed': 'Rot',
    'colorGreen': 'Grün',
    'colorBlue': 'Blau',
    'colorOrange': 'Orange',
    'colorPurple': 'Lila',
    'colorTeal': 'Türkis',
    'exerciseBenchPress': 'Bankdrücken',
    'exerciseSquat': 'Kniebeuge',
    'exerciseDeadlift': 'Kreuzheben',
    'exerciseShoulderPress': 'Schulterdrücken',
    'exercisePullUp': 'Klimmzüge',
    'exerciseRow': 'Rudern',
    'addExercise': 'Neue Übung',
    'exerciseName': 'Übungsname',
    'cancel': 'Abbrechen',
    'delete': 'Löschen',
    'add': 'Hinzufügen',
    'confirmDeleteTitle': 'Wirklich löschen?',
    'confirmDeleteMessage':
        'Diese Aktion kann nicht rückgängig gemacht werden.',
    'entriesTab': 'Einträge',
    'progressTab': 'Verlauf',
    'notEnoughData':
        'Noch nicht genug Daten -- trag deine Maximalkraft an mindestens 2 Trainingstagen ein',
    'newEntry': 'Maximalkraft eintragen',
    'maxWeightKg': 'Maximalgewicht (kg)',
    'noEntriesYet':
        'Noch keine Einträge -- trag nach deiner nächsten Trainingseinheit deine Maximalkraft ein',
    'lastEntry': 'Zuletzt',
    'weekdayMonday': 'Montag',
    'weekdayTuesday': 'Dienstag',
    'weekdayWednesday': 'Mittwoch',
    'weekdayThursday': 'Donnerstag',
    'weekdayFriday': 'Freitag',
    'weekdaySaturday': 'Samstag',
    'weekdaySunday': 'Sonntag',
    'categoryStrength': 'Kraft',
    'categoryBoxing': 'Boxen',
    'categorySparring': 'Sparring',
    'categoryCardio': 'Cardio',
    'categoryTechnique': 'Technik',
    'categoryRest': 'Ruhetag',
    'addSession': 'Einheit hinzufügen',
    'customCategoryLabel': 'Eigene Kategorie',
    'noSessionsPlanned': 'Kein Training geplant',
    'trainingTypeTechnique': 'Technik',
    'trainingTypeSparring': 'Sparring',
    'trainingTypeBoxing': 'Boxen',
    'trainingTypeMuayThai': 'Muay Thai',
    'trainingTypeKickboxing': 'Kickboxen',
    'trainingTypeMma': 'MMA',
    'trainingTypeStrength': 'Krafttraining',
    'trainingTypeCardio': 'Cardio',
    'trainingTypeOther': 'Sonstiges',
    'intensityLight': 'Leicht',
    'intensityMedium': 'Mittel',
    'intensityHard': 'Hart',
    'intensityVeryHard': 'Sehr hart',
    'moodFrustrated': 'Frustriert',
    'moodNeutral': 'Neutral',
    'moodGood': 'Gut',
    'moodMotivated': 'Motiviert',
    'moodOnFire': 'On Fire',
    'priorityLow': 'Niedrig',
    'priorityMedium': 'Mittel',
    'priorityHigh': 'Hoch',
    'statusActive': 'Aktiv',
    'statusPaused': 'Pausiert',
    'statusCompleted': 'Abgeschlossen',
    'skillAreaTechnique': 'Technik',
    'skillAreaDefense': 'Defense',
    'skillAreaFootwork': 'Beinarbeit',
    'skillAreaCondition': 'Kondition',
    'skillAreaMental': 'Mental',
    'goalRatingNone': 'Gar nicht',
    'goalRatingPartial': 'Teilweise',
    'goalRatingGood': 'Gut',
    'goalRatingGreat': 'Sehr gut',
    'logbookDashboardTab': 'Übersicht',
    'logbookHistoryTab': 'Historie',
    'logbookAnalysisTab': 'Auswertung',
    'analysisRange7d': '7 Tage',
    'analysisRange30d': '30 Tage',
    'analysisRange90d': '90 Tage',
    'analysisRangeAll': 'Alle',
    'analysisSessionsInRange': 'Einheiten',
    'analysisAvgDuration': 'Ø Dauer',
    'analysisAvgRating': 'Ø Bewertung',
    'analysisAvgIntensity': 'Ø Intensität',
    'analysisRatingTrend': 'Bewertungsverlauf',
    'analysisIntensityTrend': 'Intensitätsverlauf',
    'analysisTypeDistribution': 'Trainingsverteilung',
    'analysisTechniqueTrend': 'Technik-Erfolg',
    'analysisPainZones': 'Schmerzen nach Körperzone',
    'analysisNotEnoughData':
        'Noch nicht genug Daten in diesem Zeitraum für einen Trend.',
    'analysisNoDataInRange': 'Keine Einträge in diesem Zeitraum.',
    'statEntries': 'Trainingseinträge',
    'statTrainingDays': 'Trainingstage',
    'statActiveGoals': 'Aktive Ziele',
    'statCompletedGoals': 'Abgeschlossen',
    'statStreak': 'Trainingsserie',
    'myGoals': 'Meine aktuellen Ziele',
    'noGoalsYet':
        'Noch keine Ziele -- erstelle eins aus einem Trainingseintrag',
    'otherGoals': 'Weitere Ziele',
    'todaysFocus': 'Dein Fokus heute',
    'noFocusYet': 'Noch kein Fokus festgelegt.',
    'setFocus': 'Fokus festlegen',
    'todaysTask': 'Aufgabe für heute',
    'addTrainingEntry': 'Training eintragen',
    'developmentStarts': 'Deine Entwicklung beginnt heute.',
    'developmentStartsSubtitle':
        'Dokumentiere dein erstes Training und entdecke, worin du besser wirst.',
    'entryDate': 'Datum',
    'trainingTypeLabel': 'Trainingsart',
    'intensityLabel': 'Trainingsintensität',
    'howWasTraining': 'Wie lief das Training?',
    'whatWentWellLabel': 'Was lief gut?',
    'whatWentBadLabel': 'Was lief schlecht?',
    'improvementLabel': 'Was möchte ich verbessern?',
    'moodLabel': 'Stimmung / Gefühl',
    'saveEntry': 'Training speichern',
    'createGoalFromProblem': 'Ziel daraus erstellen',
    'entrySaved': 'Training gespeichert',
    'goalTitleLabel': 'Titel',
    'goalDescriptionLabel': 'Beschreibung',
    'goalCategoryLabel': 'Kategorie',
    'goalPriorityLabel': 'Priorität',
    'goalCreated': 'Ziel erstellt',
    'createGoal': 'Ziel erstellen',
    'saveGoal': 'Speichern',
    'goalProgress': 'Fortschritt',
    'rateGoalToday': 'Wie lief dein Ziel heute?',
    'goalHistory': 'Verlauf',
    'markCompleted': 'Als abgeschlossen markieren',
    'markPaused': 'Pausieren',
    'reactivate': 'Reaktivieren',
    'improvementDetected': 'Verbesserung erkannt',
    'editGoal': 'Ziel bearbeiten',
    'searchEntries': 'Suchen',
    'filterLabel': 'Filter',
    'filterDateRange': 'Zeitraum',
    'filterTrainingType': 'Trainingsart',
    'filterIntensity': 'Intensität',
    'filterRating': 'Bewertung',
    'filterCategory': 'Kategorie',
    'filterActiveGoals': 'Aktive Ziele',
    'filterCompletedGoals': 'Abgeschlossene Ziele',
    'clearFilters': 'Filter zurücksetzen',
    'noEntriesFound': 'Keine Einträge gefunden',
    'newGoalCreated': 'Neues Ziel erstellt',
    'problemLabel': 'Problem',
    'newGoalFromProblemTitle': 'Neues Verbesserungsziel',
    'done': 'Fertig',
    'durationLabel': 'Trainingsdauer',
    'minutesUnit': 'Min',
    'durationCustom': 'Eigene Dauer',
    'trainingGoalLabel': 'Trainingsziel',
    'coachTipGoal':
        'Was wolltest du heute verbessern? Zum Beispiel deinen Jab oder deine Defense.',
    'coachTipWentWell':
        'Schreib kurz auf, was heute besonders gut funktioniert hat.',
    'coachTipWentBad':
        'Trag hier ein, was schlecht lief. Sobald du etwas eingibst, kannst du per Button "Ziel daraus erstellen" ein langfristiges Verbesserungsziel daraus machen.',
    'coachTipDashboard':
        'Hier siehst du auf einen Blick, wie oft du trainierst und wie deine Ziele vorankommen.',
    'coachTourFocusSection':
        'Hier siehst du dein aktuelles Fokus-Ziel -- worauf du dich gerade am meisten konzentrieren willst.',
    'coachTourGoalsSection':
        'Hier findest du alle deine aktiven Ziele. Tipp drauf, um Fortschritt einzutragen oder sie zu bearbeiten.',
    'coachTourGoalProblem':
        'Das hast du gerade als Schwäche im Trainingseintrag notiert -- das Ziel hier greift das jetzt konkret auf.',
    'coachTourGoalTitle':
        'Gib deinem Ziel einen kurzen, klaren Titel -- z.B. "Guard verbessern".',
    'coachTourGoalDescription':
        'Beschreib hier genauer, woran du konkret arbeiten willst.',
    'coachTourGoalCategory':
        'Welchem Bereich lässt sich das Ziel zuordnen? Hilft dir später, deine Ziele zu sortieren.',
    'coachTourGoalPriority':
        'Wie wichtig ist dir das Ziel gerade? Hohe Priorität taucht in deinem Fokus zuerst auf.',
    'coachPlanIntro1':
        'Hey! Hier kannst du deine Trainingswoche im Voraus planen.',
    'coachPlanIntro2':
        'Leg für jeden Tag fest, was du trainieren willst -- bis zu zwei Einheiten pro Tag.',
    'coachPlanIntro3':
        'So behältst du den Überblick und trainierst nicht nach Zufall.',
    'coachTourNext': 'Weiter',
    'coachTourDone': 'Fertig',
    'coachTourSkip': 'Überspringen',
    'coachTourTrainingType': 'Wähle die Sportart, die du heute trainiert hast.',
    'coachTourAdditionalSports':
        'Hast du mehrere Stile in einer Einheit kombiniert? Hier kannst du weitere Sportarten ergänzen.',
    'coachTourSessionType':
        'Was für eine Art Training war das? Das entscheidet, welche Felder du gleich noch ausfüllst -- beim Sparring gibt es z.B. ein Rundenprotokoll.',
    'coachTourDuration': 'Wie lange hat die Einheit gedauert?',
    'coachTourRpe':
        'Wie hart hat sich das Training angefühlt -- 1 ist sehr leicht, 10 ist maximal.',
    'coachTourEnergy': 'Wie viel Energie hattest du VOR dem Training?',
    'coachTourFocus': 'Wie fokussiert warst du vor dem Training?',
    'coachTourSleep': 'Wie gut hast du in der letzten Nacht geschlafen?',
    'coachTourPain':
        'Hattest du Schmerzen oder Beschwerden? Das hilft uns, wiederkehrende Probleme früh zu erkennen.',
    'coachTourTechniques':
        'Welche Techniken hast du geübt? Trag sie als kurze Stichworte ein.',
    'coachTourSuccessRating':
        'Wie gut hat die Umsetzung geklappt -- zum Beispiel im Sparring oder am Sandsack?',
    'coachTourSparringLog':
        'Hier trägst du deine Runden ein und was du gelandet bzw. kassiert hast.',
    'coachTourRating':
        'Wie lief das Training insgesamt, auf einer Skala von 1 bis 5 Sternen?',
    'coachTourKeyTakeaway':
        'Was war heute dein wichtigster Erkenntnisgewinn? Ein Satz reicht.',
    'coachTourMood': 'Wie hast du dich nach dem Training gefühlt?',
    'coachTourImprovement':
        'Was möchtest du dir bis zum nächsten Mal konkret vornehmen zu verbessern?',
    'coachTourTimerModes':
        'Hier wechselst du zwischen Stoppuhr, Timer und Intervall-Timer für dein Rundentraining.',
    'coachTourStrengthIntro':
        'Hier fügst du neue Kraftübungen hinzu. Tippe später eine Übung an, um dein Maximalgewicht einzutragen und deinen Fortschritt zu sehen.',
    'wizardStepSession': 'Session',
    'wizardStepCheckIn': 'Check-in',
    'wizardStepTechnique': 'Technik & Sparring',
    'wizardStepTechniqueOnly': 'Technik',
    'wizardStepReflection': 'Reflexion',
    'wizardNext': 'Weiter',
    'wizardBack': 'Zurück',
    'wizardStepIndicator': 'Schritt {current} von {total}',
    'sessionTypeLabel': 'Session-Typ',
    'sessionTypeTechniqueDrilling': 'Technik/Drills',
    'sessionTypeSparring': 'Sparring',
    'sessionTypeCompetitionPrep': 'Wettkampfvorbereitung',
    'sessionTypeStrengthConditioning': 'S&C / Kondition',
    'sessionTypeOpenMat': 'Open Mat',
    'sessionTypeSeminar': 'Seminar',
    'rpeLabel': 'Intensität (RPE)',
    'rpeHint': '1 = sehr leicht, 10 = maximal',
    'additionalSportsLabel': 'Weitere Sportarten (optional)',
    'sportBjj': 'BJJ',
    'sportJudo': 'Judo',
    'sportWrestling': 'Wrestling',
    'sportKarate': 'Karate',
    'sportTaekwondo': 'Taekwondo',
    'sportCatchWrestling': 'Catch Wrestling',
    'sportSambo': 'Sambo',
    'painSectionLabel': 'Schmerzen & Beschwerden',
    'energyLevelLabel': 'Energie-Level',
    'focusLevelLabel': 'Fokus',
    'sleepQualityLabel': 'Schlafqualität (letzte Nacht)',
    'painToggleLabel': 'Schmerzen oder Beschwerden?',
    'addPainZone': 'Körperzone hinzufügen',
    'painIntensityLabel': 'Intensität',
    'removePainZone': 'Entfernen',
    'bodyZoneHead': 'Kopf',
    'bodyZoneNeck': 'Nacken',
    'bodyZoneShoulderLeft': 'Linke Schulter',
    'bodyZoneShoulderRight': 'Rechte Schulter',
    'bodyZoneElbowLeft': 'Linker Ellbogen',
    'bodyZoneElbowRight': 'Rechter Ellbogen',
    'bodyZoneWristLeft': 'Linkes Handgelenk',
    'bodyZoneWristRight': 'Rechtes Handgelenk',
    'bodyZoneRibs': 'Rippen',
    'bodyZoneUpperBack': 'Oberer Rücken',
    'bodyZoneLowerBack': 'Unterer Rücken',
    'bodyZoneHipLeft': 'Linke Hüfte',
    'bodyZoneHipRight': 'Rechte Hüfte',
    'bodyZoneKneeLeft': 'Linkes Knie',
    'bodyZoneKneeRight': 'Rechtes Knie',
    'bodyZoneAnkleLeft': 'Linker Knöchel',
    'bodyZoneAnkleRight': 'Rechter Knöchel',
    'bodyZoneFootLeft': 'Linker Fuß',
    'bodyZoneFootRight': 'Rechter Fuß',
    'bodyZoneOther': 'Sonstige',
    'techniquesPracticedLabel': 'Geübte Techniken',
    'addTechniqueHint': 'Technik hinzufügen...',
    'techniqueSuccessLabel': 'Wie gut hat die Umsetzung geklappt?',
    'sparringLogLabel': 'Sparring-Log',
    'roundsLabel': 'Runden',
    'roundLengthLabel': 'Rundenlänge (Min)',
    'partnerLevelLabel': 'Partner-Level',
    'partnerLevelBeginner': 'Anfänger',
    'partnerLevelEven': 'Gleichwertig',
    'partnerLevelAdvancedCoach': 'Fortgeschritten/Coach',
    'submissionsLabel': 'Submissions',
    'takedownsLabel': 'Takedowns',
    'strikesLabel': 'Treffer',
    'statFor': 'Gegeben',
    'statAgainst': 'Erhalten',
    'keyTakeawayLabel': 'Key Takeaway / Aha-Moment',
    'keyTakeawayHint': 'Was war heute dein wichtigster Erkenntnisgewinn?',
  },
  'en': {
    'appTitle': 'Boxing App',
    'tagline': 'Train. Track. Win.',
    'timer': 'Timer',
    'stopwatch': 'Stopwatch',
    'interval': 'Intervals',
    'strength': 'Strength Training',
    'trainingPlan': 'Training Plan',
    'logbook': 'Logbook',
    'settings': 'Settings',
    'comingSoon': 'Coming soon',
    'colorDesign': 'Color Theme',
    'colorDesignSubtitle': 'Default: Red -- choose your own accent color',
    'language': 'Language',
    'start': 'Start',
    'pause': 'Pause',
    'reset': 'Reset',
    'timeUp': 'Time is up!',
    'trainingDone': 'Training finished',
    'round': 'Round',
    'rounds': 'Rounds',
    'roundDuration': 'Round duration',
    'min': 'Min',
    'sec': 'Sec',
    'soundToggleTitle': 'Sound when time is up',
    'soundToggleSubtitle': 'Play the boxing bell when the timer ends',
    'colorRed': 'Red',
    'colorGreen': 'Green',
    'colorBlue': 'Blue',
    'colorOrange': 'Orange',
    'colorPurple': 'Purple',
    'colorTeal': 'Teal',
    'exerciseBenchPress': 'Bench Press',
    'exerciseSquat': 'Squat',
    'exerciseDeadlift': 'Deadlift',
    'exerciseShoulderPress': 'Shoulder Press',
    'exercisePullUp': 'Pull-Ups',
    'exerciseRow': 'Rowing',
    'addExercise': 'New Exercise',
    'exerciseName': 'Exercise name',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'add': 'Add',
    'confirmDeleteTitle': 'Delete this?',
    'confirmDeleteMessage': 'This action cannot be undone.',
    'entriesTab': 'Entries',
    'progressTab': 'Progress',
    'notEnoughData':
        'Not enough data yet -- log your max strength on at least 2 training days',
    'newEntry': 'Log max strength',
    'maxWeightKg': 'Max weight (kg)',
    'noEntriesYet':
        'No entries yet -- log your max strength after your next training session',
    'lastEntry': 'Last',
    'weekdayMonday': 'Monday',
    'weekdayTuesday': 'Tuesday',
    'weekdayWednesday': 'Wednesday',
    'weekdayThursday': 'Thursday',
    'weekdayFriday': 'Friday',
    'weekdaySaturday': 'Saturday',
    'weekdaySunday': 'Sunday',
    'categoryStrength': 'Strength',
    'categoryBoxing': 'Boxing',
    'categorySparring': 'Sparring',
    'categoryCardio': 'Cardio',
    'categoryTechnique': 'Technique',
    'categoryRest': 'Rest day',
    'addSession': 'Add session',
    'customCategoryLabel': 'Custom category',
    'noSessionsPlanned': 'No training planned',
    'trainingTypeTechnique': 'Technique',
    'trainingTypeSparring': 'Sparring',
    'trainingTypeBoxing': 'Boxing',
    'trainingTypeMuayThai': 'Muay Thai',
    'trainingTypeKickboxing': 'Kickboxing',
    'trainingTypeMma': 'MMA',
    'trainingTypeStrength': 'Strength training',
    'trainingTypeCardio': 'Cardio',
    'trainingTypeOther': 'Other',
    'intensityLight': 'Light',
    'intensityMedium': 'Medium',
    'intensityHard': 'Hard',
    'intensityVeryHard': 'Very hard',
    'moodFrustrated': 'Frustrated',
    'moodNeutral': 'Neutral',
    'moodGood': 'Good',
    'moodMotivated': 'Motivated',
    'moodOnFire': 'On fire',
    'priorityLow': 'Low',
    'priorityMedium': 'Medium',
    'priorityHigh': 'High',
    'statusActive': 'Active',
    'statusPaused': 'Paused',
    'statusCompleted': 'Completed',
    'skillAreaTechnique': 'Technique',
    'skillAreaDefense': 'Defense',
    'skillAreaFootwork': 'Footwork',
    'skillAreaCondition': 'Conditioning',
    'skillAreaMental': 'Mental',
    'goalRatingNone': 'Not at all',
    'goalRatingPartial': 'Partially',
    'goalRatingGood': 'Good',
    'goalRatingGreat': 'Great',
    'logbookDashboardTab': 'Overview',
    'logbookHistoryTab': 'History',
    'logbookAnalysisTab': 'Analysis',
    'analysisRange7d': '7 days',
    'analysisRange30d': '30 days',
    'analysisRange90d': '90 days',
    'analysisRangeAll': 'All',
    'analysisSessionsInRange': 'Sessions',
    'analysisAvgDuration': 'Avg. duration',
    'analysisAvgRating': 'Avg. rating',
    'analysisAvgIntensity': 'Avg. intensity',
    'analysisRatingTrend': 'Rating trend',
    'analysisIntensityTrend': 'Intensity trend',
    'analysisTypeDistribution': 'Training distribution',
    'analysisTechniqueTrend': 'Technique success',
    'analysisPainZones': 'Pain by body zone',
    'analysisNotEnoughData': 'Not enough data in this range yet for a trend.',
    'analysisNoDataInRange': 'No entries in this range.',
    'statEntries': 'Training entries',
    'statTrainingDays': 'Training days',
    'statActiveGoals': 'Active goals',
    'statCompletedGoals': 'Completed',
    'statStreak': 'Training streak',
    'myGoals': 'My current goals',
    'noGoalsYet': 'No goals yet -- create one from a training entry',
    'otherGoals': 'Other goals',
    'todaysFocus': 'Your focus today',
    'noFocusYet': 'No focus set yet.',
    'setFocus': 'Set focus',
    'todaysTask': "Today's task",
    'addTrainingEntry': 'Log training',
    'developmentStarts': 'Your development starts today.',
    'developmentStartsSubtitle':
        'Log your first training session and discover what you get better at.',
    'entryDate': 'Date',
    'trainingTypeLabel': 'Training type',
    'intensityLabel': 'Training intensity',
    'howWasTraining': 'How was the training?',
    'whatWentWellLabel': 'What went well?',
    'whatWentBadLabel': 'What went badly?',
    'improvementLabel': 'What do I want to improve?',
    'moodLabel': 'Mood / feeling',
    'saveEntry': 'Save training',
    'createGoalFromProblem': 'Create a goal from this',
    'entrySaved': 'Training saved',
    'goalTitleLabel': 'Title',
    'goalDescriptionLabel': 'Description',
    'goalCategoryLabel': 'Category',
    'goalPriorityLabel': 'Priority',
    'goalCreated': 'Goal created',
    'createGoal': 'Create goal',
    'saveGoal': 'Save',
    'goalProgress': 'Progress',
    'rateGoalToday': 'How did your goal go today?',
    'goalHistory': 'History',
    'markCompleted': 'Mark as completed',
    'markPaused': 'Pause',
    'reactivate': 'Reactivate',
    'improvementDetected': 'Improvement detected',
    'editGoal': 'Edit goal',
    'searchEntries': 'Search',
    'filterLabel': 'Filter',
    'filterDateRange': 'Date range',
    'filterTrainingType': 'Training type',
    'filterIntensity': 'Intensity',
    'filterRating': 'Rating',
    'filterCategory': 'Category',
    'filterActiveGoals': 'Active goals',
    'filterCompletedGoals': 'Completed goals',
    'clearFilters': 'Clear filters',
    'noEntriesFound': 'No entries found',
    'newGoalCreated': 'New goal created',
    'problemLabel': 'Problem',
    'newGoalFromProblemTitle': 'New improvement goal',
    'done': 'Done',
    'durationLabel': 'Training duration',
    'minutesUnit': 'min',
    'durationCustom': 'Custom duration',
    'trainingGoalLabel': 'Training goal',
    'coachTipGoal':
        'What did you want to work on today? Like your jab or your defense.',
    'coachTipWentWell': 'Jot down what worked especially well today.',
    'coachTipWentBad':
        'Note what went badly. Once you type something, the "Create a goal from this" button turns it into a long-term improvement goal.',
    'coachTipDashboard':
        "Here's your training at a glance -- how often you train and how your goals are coming along.",
    'coachTourFocusSection':
        "This shows your current focus goal -- whatever you want to concentrate on most right now.",
    'coachTourGoalsSection':
        "Here you'll find all your active goals. Tap one to log progress or edit it.",
    'coachTourGoalProblem':
        "This is the weakness you just noted in your training entry -- this goal builds on it directly.",
    'coachTourGoalTitle':
        'Give your goal a short, clear title -- e.g. "Improve guard".',
    'coachTourGoalDescription':
        'Describe in more detail what exactly you want to work on.',
    'coachTourGoalCategory':
        'Which area does this goal belong to? Helps you sort your goals later.',
    'coachTourGoalPriority':
        'How important is this goal right now? High-priority goals show up first in your focus.',
    'coachPlanIntro1':
        'Hey! This is where you plan your training week ahead of time.',
    'coachPlanIntro2':
        'Set what you want to train each day -- up to two sessions per day.',
    'coachPlanIntro3':
        "That way you stay on track instead of training at random.",
    'coachTourNext': 'Next',
    'coachTourDone': 'Done',
    'coachTourSkip': 'Skip',
    'coachTourTrainingType': 'Pick the discipline you trained today.',
    'coachTourAdditionalSports':
        'Combined multiple styles in one session? Add extra disciplines here.',
    'coachTourSessionType':
        "What kind of session was it? This decides which fields you'll fill in next -- sparring unlocks a round-by-round log, for example.",
    'coachTourDuration': 'How long did the session last?',
    'coachTourRpe': 'How hard did it feel -- 1 is very easy, 10 is maximal.',
    'coachTourEnergy': 'How much energy did you have BEFORE training?',
    'coachTourFocus': 'How focused were you before training?',
    'coachTourSleep': 'How well did you sleep last night?',
    'coachTourPain':
        'Any pain or discomfort? This helps us spot recurring issues early.',
    'coachTourTechniques':
        'Which techniques did you drill? Add them as short tags.',
    'coachTourSuccessRating':
        'How well did it translate -- in sparring or on the bag, for example?',
    'coachTourSparringLog':
        "Here's where you log your rounds and what you landed or took.",
    'coachTourRating':
        'How did the session go overall, on a scale of 1 to 5 stars?',
    'coachTourKeyTakeaway':
        "What was today's biggest takeaway? One sentence is enough.",
    'coachTourMood': 'How did you feel after training?',
    'coachTourImprovement':
        'What do you want to specifically work on improving by next time?',
    'coachTourTimerModes':
        'Switch here between stopwatch, timer, and interval timer for your round training.',
    'coachTourStrengthIntro':
        'Add new strength exercises here. Later, tap an exercise to log your max weight and track your progress.',
    'wizardStepSession': 'Session',
    'wizardStepCheckIn': 'Check-in',
    'wizardStepTechnique': 'Technique & Sparring',
    'wizardStepTechniqueOnly': 'Technique',
    'wizardStepReflection': 'Reflection',
    'wizardNext': 'Next',
    'wizardBack': 'Back',
    'wizardStepIndicator': 'Step {current} of {total}',
    'sessionTypeLabel': 'Session type',
    'sessionTypeTechniqueDrilling': 'Technique/Drilling',
    'sessionTypeSparring': 'Sparring',
    'sessionTypeCompetitionPrep': 'Competition prep',
    'sessionTypeStrengthConditioning': 'S&C / Conditioning',
    'sessionTypeOpenMat': 'Open mat',
    'sessionTypeSeminar': 'Seminar',
    'rpeLabel': 'Intensity (RPE)',
    'rpeHint': '1 = very easy, 10 = maximal',
    'additionalSportsLabel': 'Additional disciplines (optional)',
    'sportBjj': 'BJJ',
    'sportJudo': 'Judo',
    'sportWrestling': 'Wrestling',
    'sportKarate': 'Karate',
    'sportTaekwondo': 'Taekwondo',
    'sportCatchWrestling': 'Catch wrestling',
    'sportSambo': 'Sambo',
    'painSectionLabel': 'Pain & discomfort',
    'energyLevelLabel': 'Energy level',
    'focusLevelLabel': 'Focus',
    'sleepQualityLabel': 'Sleep quality (last night)',
    'painToggleLabel': 'Pain or discomfort?',
    'addPainZone': 'Add body area',
    'painIntensityLabel': 'Intensity',
    'removePainZone': 'Remove',
    'bodyZoneHead': 'Head',
    'bodyZoneNeck': 'Neck',
    'bodyZoneShoulderLeft': 'Left shoulder',
    'bodyZoneShoulderRight': 'Right shoulder',
    'bodyZoneElbowLeft': 'Left elbow',
    'bodyZoneElbowRight': 'Right elbow',
    'bodyZoneWristLeft': 'Left wrist',
    'bodyZoneWristRight': 'Right wrist',
    'bodyZoneRibs': 'Ribs',
    'bodyZoneUpperBack': 'Upper back',
    'bodyZoneLowerBack': 'Lower back',
    'bodyZoneHipLeft': 'Left hip',
    'bodyZoneHipRight': 'Right hip',
    'bodyZoneKneeLeft': 'Left knee',
    'bodyZoneKneeRight': 'Right knee',
    'bodyZoneAnkleLeft': 'Left ankle',
    'bodyZoneAnkleRight': 'Right ankle',
    'bodyZoneFootLeft': 'Left foot',
    'bodyZoneFootRight': 'Right foot',
    'bodyZoneOther': 'Other',
    'techniquesPracticedLabel': 'Techniques practiced',
    'addTechniqueHint': 'Add technique...',
    'techniqueSuccessLabel': 'How well did it translate?',
    'sparringLogLabel': 'Sparring log',
    'roundsLabel': 'Rounds',
    'roundLengthLabel': 'Round length (min)',
    'partnerLevelLabel': 'Partner level',
    'partnerLevelBeginner': 'Beginner',
    'partnerLevelEven': 'Even',
    'partnerLevelAdvancedCoach': 'Advanced/Coach',
    'submissionsLabel': 'Submissions',
    'takedownsLabel': 'Takedowns',
    'strikesLabel': 'Strikes',
    'statFor': 'Landed',
    'statAgainst': 'Received',
    'keyTakeawayLabel': 'Key takeaway / aha moment',
    'keyTakeawayHint': "What was today's biggest insight?",
  },
};

/// Kleine, selbstgebaute Übersetzungslösung statt Flutters offiziellem
/// l10n-Codegen (ARB-Dateien + flutter gen-l10n) -- für den aktuellen Umfang
/// reicht eine einfache Lookup-Tabelle.
class AppStrings {
  const AppStrings(this._map);

  factory AppStrings.of(Locale locale) {
    return AppStrings(
      _translations[locale.languageCode] ?? _translations['de']!,
    );
  }

  final Map<String, String> _map;

  String call(String key) => _map[key] ?? key;
}
