import 'package:flutter/material.dart';

const Map<String, Map<String, String>> _translations = {
  'de': {
    'appTitle': 'Boxing App',
    'tagline': 'Train. Track. Win.',
    'timer': 'Timer',
    'stopwatch': 'Stoppuhr',
    'interval': 'Intervalle',
    'strength': 'Kraftübungen',
    'trainingPlan': 'Trainingsplan',
    'logbook': 'Logbuch',
    'settings': 'Einstellungen',
    'comingSoon': 'Bald verfügbar',
    'colorDesign': 'Farbdesign',
    'colorDesignSubtitle': 'Standard: Rot -- wähle deine eigene Akzentfarbe',
    'language': 'Sprache',
    'start': 'Start',
    'pause': 'Pause',
    'reset': 'Reset',
    'timeUp': 'Zeit abgelaufen!',
    'trainingDone': 'Training beendet',
    'round': 'Runde',
    'rounds': 'Runden',
    'roundDuration': 'Rundendauer',
    'min': 'Min',
    'sec': 'Sek',
    'soundToggleTitle': 'Signalton bei Zeitablauf',
    'soundToggleSubtitle': 'Boxglocke abspielen, wenn der Timer abläuft',
    'colorRed': 'Rot',
    'colorGreen': 'Grün',
    'colorBlue': 'Blau',
    'colorOrange': 'Orange',
    'colorPurple': 'Lila',
    'colorTeal': 'Türkis',
    'exerciseBenchPress': 'Bankdrücken',
    'exerciseSquat': 'Kniebeuge',
    'exerciseDeadlift': 'Kreuzheben',
    'exerciseShoulderPress': 'Schulterdrücken',
    'exercisePullUp': 'Klimmzüge',
    'exerciseRow': 'Rudern',
    'addExercise': 'Neue Übung',
    'exerciseName': 'Übungsname',
    'cancel': 'Abbrechen',
    'delete': 'Löschen',
    'add': 'Hinzufügen',
    'exerciseDeleted': 'Übung gelöscht',
    'undo': 'Rückgängig',
    'entriesTab': 'Einträge',
    'progressTab': 'Verlauf',
    'notEnoughData': 'Noch nicht genug Daten -- trag deine Maximalkraft an mindestens 2 Trainingstagen ein',
    'newEntry': 'Maximalkraft eintragen',
    'maxWeightKg': 'Maximalgewicht (kg)',
    'noEntriesYet': 'Noch keine Einträge -- trag nach deiner nächsten Trainingseinheit deine Maximalkraft ein',
    'lastEntry': 'Zuletzt',
    'entryDeleted': 'Eintrag gelöscht',
    'weekdayMonday': 'Montag',
    'weekdayTuesday': 'Dienstag',
    'weekdayWednesday': 'Mittwoch',
    'weekdayThursday': 'Donnerstag',
    'weekdayFriday': 'Freitag',
    'weekdaySaturday': 'Samstag',
    'weekdaySunday': 'Sonntag',
    'categoryStrength': 'Kraft',
    'categoryBoxing': 'Boxen',
    'categorySparring': 'Sparring',
    'categoryCardio': 'Cardio',
    'categoryTechnique': 'Technik',
    'categoryRest': 'Ruhetag',
    'addSession': 'Einheit hinzufügen',
    'customCategoryLabel': 'Eigene Kategorie',
    'noSessionsPlanned': 'Kein Training geplant',
    'sessionDeleted': 'Einheit gelöscht',
    'trainingTypeTechnique': 'Technik',
    'trainingTypeSparring': 'Sparring',
    'trainingTypeBoxing': 'Boxtraining',
    'trainingTypeMuayThai': 'Muay Thai',
    'trainingTypeKickboxing': 'Kickboxen',
    'trainingTypeMma': 'MMA',
    'trainingTypeStrength': 'Krafttraining',
    'trainingTypeCardio': 'Cardio',
    'trainingTypeOther': 'Sonstiges',
    'intensityLight': 'Leicht',
    'intensityMedium': 'Mittel',
    'intensityHard': 'Hart',
    'intensityVeryHard': 'Sehr hart',
    'moodFrustrated': 'Frustriert',
    'moodNeutral': 'Neutral',
    'moodGood': 'Gut',
    'moodMotivated': 'Motiviert',
    'moodOnFire': 'On Fire',
    'priorityLow': 'Niedrig',
    'priorityMedium': 'Mittel',
    'priorityHigh': 'Hoch',
    'statusActive': 'Aktiv',
    'statusPaused': 'Pausiert',
    'statusCompleted': 'Abgeschlossen',
    'skillAreaTechnique': 'Technik',
    'skillAreaDefense': 'Defense',
    'skillAreaFootwork': 'Beinarbeit',
    'skillAreaCondition': 'Kondition',
    'skillAreaMental': 'Mental',
    'skillJab': 'Jab',
    'skillCross': 'Cross',
    'skillHook': 'Hook',
    'skillUppercut': 'Uppercut',
    'skillCombinations': 'Kombinationen',
    'skillGuard': 'Deckung',
    'skillHeadMovement': 'Kopfbewegung',
    'skillBlocks': 'Blocks',
    'skillDistance': 'Distanz',
    'skillFootwork': 'Footwork',
    'skillAngles': 'Winkel',
    'skillRingControl': 'Ringkontrolle',
    'skillEndurance': 'Ausdauer',
    'skillExplosiveness': 'Explosivität',
    'skillRecovery': 'Erholung',
    'skillFocus': 'Fokus',
    'skillCalm': 'Ruhe',
    'skillConfidence': 'Selbstvertrauen',
    'skillDiscipline': 'Disziplin',
    'goalRatingNone': 'Gar nicht',
    'goalRatingPartial': 'Teilweise',
    'goalRatingGood': 'Gut',
    'goalRatingGreat': 'Sehr gut',
    'logbookDashboardTab': 'Übersicht',
    'logbookHistoryTab': 'Historie',
    'logbookProgressTab': 'Entwicklung',
    'statEntries': 'Trainingseinträge',
    'statTrainingDays': 'Trainingstage',
    'statActiveGoals': 'Aktive Ziele',
    'statCompletedGoals': 'Abgeschlossen',
    'statStreak': 'Trainingsserie',
    'myGoals': 'Meine aktuellen Ziele',
    'noGoalsYet': 'Noch keine Ziele -- erstelle eins aus einem Trainingseintrag',
    'todaysFocus': 'Dein Fokus heute',
    'noFocusYet': 'Noch kein Fokus festgelegt.',
    'setFocus': 'Fokus festlegen',
    'todaysTask': 'Aufgabe für heute',
    'addTrainingEntry': 'Training eintragen',
    'developmentStarts': 'Deine Entwicklung beginnt heute.',
    'developmentStartsSubtitle':
        'Dokumentiere dein erstes Training und entdecke, worin du besser wirst.',
    'entryDate': 'Datum',
    'trainingTypeLabel': 'Trainingsart',
    'intensityLabel': 'Trainingsintensität',
    'howWasTraining': 'Wie lief das Training?',
    'whatWentWellLabel': 'Was lief gut?',
    'whatWentBadLabel': 'Was lief schlecht?',
    'improvementLabel': 'Was möchte ich verbessern?',
    'moodLabel': 'Stimmung / Gefühl',
    'saveEntry': 'Training speichern',
    'createGoalFromProblem': 'Ziel daraus erstellen',
    'entrySaved': 'Training gespeichert',
    'goalTitleLabel': 'Titel',
    'goalDescriptionLabel': 'Beschreibung',
    'goalCategoryLabel': 'Kategorie',
    'goalPriorityLabel': 'Priorität',
    'goalCreated': 'Ziel erstellt',
    'createGoal': 'Ziel erstellen',
    'saveGoal': 'Speichern',
    'goalProgress': 'Fortschritt',
    'rateGoalToday': 'Wie lief dein Ziel heute?',
    'goalHistory': 'Verlauf',
    'markCompleted': 'Als abgeschlossen markieren',
    'markPaused': 'Pausieren',
    'reactivate': 'Reaktivieren',
    'improvementDetected': 'Verbesserung erkannt',
    'goalDeleted': 'Ziel gelöscht',
    'editGoal': 'Ziel bearbeiten',
    'searchEntries': 'Suchen',
    'filterLabel': 'Filter',
    'filterDateRange': 'Zeitraum',
    'filterTrainingType': 'Trainingsart',
    'filterIntensity': 'Intensität',
    'filterRating': 'Bewertung',
    'filterCategory': 'Kategorie',
    'filterActiveGoals': 'Aktive Ziele',
    'filterCompletedGoals': 'Abgeschlossene Ziele',
    'clearFilters': 'Filter zurücksetzen',
    'noEntriesFound': 'Keine Einträge gefunden',
    'newGoalCreated': 'Neues Ziel erstellt',
    'myDevelopment': 'Meine Entwicklung',
    'selfAssessmentNote': 'Selbsteinschätzung, keine objektive Leistungsmessung',
    'notEnoughSkillData': 'Noch nicht genug Selbsteinschätzungen für diesen Bereich',
    'problemLabel': 'Problem',
    'newGoalFromProblemTitle': 'Neues Verbesserungsziel',
    'done': 'Fertig',
  },
  'en': {
    'appTitle': 'Boxing App',
    'tagline': 'Train. Track. Win.',
    'timer': 'Timer',
    'stopwatch': 'Stopwatch',
    'interval': 'Intervals',
    'strength': 'Strength Training',
    'trainingPlan': 'Training Plan',
    'logbook': 'Logbook',
    'settings': 'Settings',
    'comingSoon': 'Coming soon',
    'colorDesign': 'Color Theme',
    'colorDesignSubtitle': 'Default: Red -- choose your own accent color',
    'language': 'Language',
    'start': 'Start',
    'pause': 'Pause',
    'reset': 'Reset',
    'timeUp': 'Time is up!',
    'trainingDone': 'Training finished',
    'round': 'Round',
    'rounds': 'Rounds',
    'roundDuration': 'Round duration',
    'min': 'Min',
    'sec': 'Sec',
    'soundToggleTitle': 'Sound when time is up',
    'soundToggleSubtitle': 'Play the boxing bell when the timer ends',
    'colorRed': 'Red',
    'colorGreen': 'Green',
    'colorBlue': 'Blue',
    'colorOrange': 'Orange',
    'colorPurple': 'Purple',
    'colorTeal': 'Teal',
    'exerciseBenchPress': 'Bench Press',
    'exerciseSquat': 'Squat',
    'exerciseDeadlift': 'Deadlift',
    'exerciseShoulderPress': 'Shoulder Press',
    'exercisePullUp': 'Pull-Ups',
    'exerciseRow': 'Rowing',
    'addExercise': 'New Exercise',
    'exerciseName': 'Exercise name',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'add': 'Add',
    'exerciseDeleted': 'Exercise deleted',
    'undo': 'Undo',
    'entriesTab': 'Entries',
    'progressTab': 'Progress',
    'notEnoughData': 'Not enough data yet -- log your max strength on at least 2 training days',
    'newEntry': 'Log max strength',
    'maxWeightKg': 'Max weight (kg)',
    'noEntriesYet': 'No entries yet -- log your max strength after your next training session',
    'lastEntry': 'Last',
    'entryDeleted': 'Entry deleted',
    'weekdayMonday': 'Monday',
    'weekdayTuesday': 'Tuesday',
    'weekdayWednesday': 'Wednesday',
    'weekdayThursday': 'Thursday',
    'weekdayFriday': 'Friday',
    'weekdaySaturday': 'Saturday',
    'weekdaySunday': 'Sunday',
    'categoryStrength': 'Strength',
    'categoryBoxing': 'Boxing',
    'categorySparring': 'Sparring',
    'categoryCardio': 'Cardio',
    'categoryTechnique': 'Technique',
    'categoryRest': 'Rest day',
    'addSession': 'Add session',
    'customCategoryLabel': 'Custom category',
    'noSessionsPlanned': 'No training planned',
    'sessionDeleted': 'Session deleted',
    'trainingTypeTechnique': 'Technique',
    'trainingTypeSparring': 'Sparring',
    'trainingTypeBoxing': 'Boxing training',
    'trainingTypeMuayThai': 'Muay Thai',
    'trainingTypeKickboxing': 'Kickboxing',
    'trainingTypeMma': 'MMA',
    'trainingTypeStrength': 'Strength training',
    'trainingTypeCardio': 'Cardio',
    'trainingTypeOther': 'Other',
    'intensityLight': 'Light',
    'intensityMedium': 'Medium',
    'intensityHard': 'Hard',
    'intensityVeryHard': 'Very hard',
    'moodFrustrated': 'Frustrated',
    'moodNeutral': 'Neutral',
    'moodGood': 'Good',
    'moodMotivated': 'Motivated',
    'moodOnFire': 'On fire',
    'priorityLow': 'Low',
    'priorityMedium': 'Medium',
    'priorityHigh': 'High',
    'statusActive': 'Active',
    'statusPaused': 'Paused',
    'statusCompleted': 'Completed',
    'skillAreaTechnique': 'Technique',
    'skillAreaDefense': 'Defense',
    'skillAreaFootwork': 'Footwork',
    'skillAreaCondition': 'Conditioning',
    'skillAreaMental': 'Mental',
    'skillJab': 'Jab',
    'skillCross': 'Cross',
    'skillHook': 'Hook',
    'skillUppercut': 'Uppercut',
    'skillCombinations': 'Combinations',
    'skillGuard': 'Guard',
    'skillHeadMovement': 'Head movement',
    'skillBlocks': 'Blocks',
    'skillDistance': 'Distance',
    'skillFootwork': 'Footwork',
    'skillAngles': 'Angles',
    'skillRingControl': 'Ring control',
    'skillEndurance': 'Endurance',
    'skillExplosiveness': 'Explosiveness',
    'skillRecovery': 'Recovery',
    'skillFocus': 'Focus',
    'skillCalm': 'Calm',
    'skillConfidence': 'Confidence',
    'skillDiscipline': 'Discipline',
    'goalRatingNone': 'Not at all',
    'goalRatingPartial': 'Partially',
    'goalRatingGood': 'Good',
    'goalRatingGreat': 'Great',
    'logbookDashboardTab': 'Overview',
    'logbookHistoryTab': 'History',
    'logbookProgressTab': 'Progress',
    'statEntries': 'Training entries',
    'statTrainingDays': 'Training days',
    'statActiveGoals': 'Active goals',
    'statCompletedGoals': 'Completed',
    'statStreak': 'Training streak',
    'myGoals': 'My current goals',
    'noGoalsYet': 'No goals yet -- create one from a training entry',
    'todaysFocus': 'Your focus today',
    'noFocusYet': 'No focus set yet.',
    'setFocus': 'Set focus',
    'todaysTask': "Today's task",
    'addTrainingEntry': 'Log training',
    'developmentStarts': 'Your development starts today.',
    'developmentStartsSubtitle':
        'Log your first training session and discover what you get better at.',
    'entryDate': 'Date',
    'trainingTypeLabel': 'Training type',
    'intensityLabel': 'Training intensity',
    'howWasTraining': 'How was the training?',
    'whatWentWellLabel': 'What went well?',
    'whatWentBadLabel': 'What went badly?',
    'improvementLabel': 'What do I want to improve?',
    'moodLabel': 'Mood / feeling',
    'saveEntry': 'Save training',
    'createGoalFromProblem': 'Create a goal from this',
    'entrySaved': 'Training saved',
    'goalTitleLabel': 'Title',
    'goalDescriptionLabel': 'Description',
    'goalCategoryLabel': 'Category',
    'goalPriorityLabel': 'Priority',
    'goalCreated': 'Goal created',
    'createGoal': 'Create goal',
    'saveGoal': 'Save',
    'goalProgress': 'Progress',
    'rateGoalToday': 'How did your goal go today?',
    'goalHistory': 'History',
    'markCompleted': 'Mark as completed',
    'markPaused': 'Pause',
    'reactivate': 'Reactivate',
    'improvementDetected': 'Improvement detected',
    'goalDeleted': 'Goal deleted',
    'editGoal': 'Edit goal',
    'searchEntries': 'Search',
    'filterLabel': 'Filter',
    'filterDateRange': 'Date range',
    'filterTrainingType': 'Training type',
    'filterIntensity': 'Intensity',
    'filterRating': 'Rating',
    'filterCategory': 'Category',
    'filterActiveGoals': 'Active goals',
    'filterCompletedGoals': 'Completed goals',
    'clearFilters': 'Clear filters',
    'noEntriesFound': 'No entries found',
    'newGoalCreated': 'New goal created',
    'myDevelopment': 'My development',
    'selfAssessmentNote': 'Self-assessment, not an objective performance measure',
    'notEnoughSkillData': 'Not enough self-assessments for this area yet',
    'problemLabel': 'Problem',
    'newGoalFromProblemTitle': 'New improvement goal',
    'done': 'Done',
  },
};

/// Kleine, selbstgebaute Übersetzungslösung statt Flutters offiziellem
/// l10n-Codegen (ARB-Dateien + flutter gen-l10n) -- für den aktuellen Umfang
/// reicht eine einfache Lookup-Tabelle.
class AppStrings {
  const AppStrings(this._map);

  factory AppStrings.of(Locale locale) {
    return AppStrings(_translations[locale.languageCode] ?? _translations['de']!);
  }

  final Map<String, String> _map;

  String call(String key) => _map[key] ?? key;
}
